set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[15] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[14] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[13] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[12] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[11] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[10] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[9] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[8] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[7] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[6] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[5] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[4] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[3] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[2] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[1] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/adder_out_reg[0] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/a_reg_reg[3] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/a_reg_reg[2] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/a_reg_reg[1] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/a_reg_reg[0] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/b_reg_reg[3] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/b_reg_reg[2] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/b_reg_reg[1] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/b_reg_reg[0] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/diff_reg_reg[4] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/diff_reg_reg[3] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[8] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[7] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[6] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[5] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[4] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[3] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[2] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/m_reg_reg[0] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/sload_reg_reg -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/diff_reg_reg[2] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/diff_reg_reg[1] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/diff_reg_reg[0] -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U2 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U3 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U4 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U5 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U6 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U7 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U8 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U9 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U10 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U11 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U12 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U13 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U14 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U15 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U16 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U17 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U18 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U19 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U20 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U21 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U22 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U23 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U24 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U25 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U26 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U27 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U28 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U29 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U30 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U31 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U32 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U33 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U34 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U35 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U36 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U37 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U38 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U39 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U40 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U41 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U42 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U43 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U44 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U45 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U46 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U47 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U48 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U49 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U50 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U51 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U52 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U53 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U54 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U55 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U56 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U57 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U58 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U59 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U60 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U61 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U62 -status unplaced
set_cell_placement_status -name u_macc_top/macc[0].u_macc/U63 -status unplaced